# Generated by Django 6.1.1 on 2026-10-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('order', 'Order'), ('custom', 'Custom'), ('wholesale', 'Wholesale'), ('hello', 'Hello')], default='hello', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('want', models.TextField()),
                ('colors', models.CharField(blank=True, max_length=160)),
                ('size', models.CharField(blank=True, max_length=160)),
                ('timing', models.CharField(blank=True, max_length=160)),
                ('photo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stitching', 'Stitching'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('method', models.CharField(choices=[('ship', 'Ship'), ('pickup', 'Local pickup')], max_length=16)),
                ('street', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('postal', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('gift_wrap', models.BooleanField(default=False)),
                ('gift_wrap_cents', models.PositiveIntegerField(default=0)),
                ('subtotal_cents', models.PositiveIntegerField()),
                ('sample', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StitchSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='studio.order')),
            ],
        ),
    ]
