# Generated by Django 6.1.1 on 2026-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(default='Made to order in small batches · ships in 5–10 days', max_length=180)),
                ('gift_wrap_cents', models.PositiveIntegerField(default=600)),
            ],
        ),
    ]
